// <auto-generated />
using System;
using BlazingPizzaSite.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazingPizzaSite.Infrastructure.Migrations
{
    [DbContext(typeof(SimplePizzaCatalogDbContext))]
    [Migration("20240401105309_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("BlazingPizzaSite.Domain.Entities.Pizza", b =>
                {
                    b.Property<Guid>("PizzaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DougtType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("Toppings")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Vegan")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Vegetarian")
                        .HasColumnType("INTEGER");

                    b.Property<string>("size")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PizzaId");

                    b.ToTable("Pizzas");

                    b.HasData(
                        new
                        {
                            PizzaId = new Guid("60887d37-769c-4962-b9ab-1ce69691da3e"),
                            Category = 0,
                            Description = "Pepperoni, Sausage, Canadian Bacon, Bacon, Mozzarella",
                            DougtType = "",
                            Name = "Meat Pizza",
                            Price = 12.50m,
                            Toppings = "[]",
                            Vegan = false,
                            Vegetarian = false,
                            size = ""
                        },
                        new
                        {
                            PizzaId = new Guid("d48d3636-a4b6-4ba9-ada1-dd4208d97e98"),
                            Category = 1,
                            Description = "Grilled Chicken, BBQ Sauce, Red Onion, Cilantro, Mozzarella",
                            DougtType = "",
                            Name = "Chicken Pizza",
                            Price = 11.50m,
                            Toppings = "[]",
                            Vegan = false,
                            Vegetarian = false,
                            size = ""
                        },
                        new
                        {
                            PizzaId = new Guid("4816d0d8-c2bc-4ee6-b703-de461744c78f"),
                            Category = 2,
                            Description = "Mushrooms, Olives, Green Peppers, Onions, Mozzarella",
                            DougtType = "",
                            Name = "Vegetarian Pizza",
                            Price = 10.00m,
                            Toppings = "[]",
                            Vegan = false,
                            Vegetarian = false,
                            size = ""
                        },
                        new
                        {
                            PizzaId = new Guid("31d10122-574c-4564-aadf-d9d0af852d9d"),
                            Category = 3,
                            Description = "Mushrooms, Olives, Green Peppers, Onions, Vegan Cheese",
                            DougtType = "",
                            Name = "Vegan Pizza",
                            Price = 10.00m,
                            Toppings = "[]",
                            Vegan = false,
                            Vegetarian = false,
                            size = ""
                        },
                        new
                        {
                            PizzaId = new Guid("ddddcd1f-27ec-4987-9bbf-e9308474cadc"),
                            Category = 4,
                            Description = "Gluten-Free Crust, Mushrooms, Olives, Green Peppers, Onions, Mozzarella",
                            DougtType = "",
                            Name = "Gluten-Free Pizza",
                            Price = 14.00m,
                            Toppings = "[]",
                            Vegan = false,
                            Vegetarian = false,
                            size = ""
                        },
                        new
                        {
                            PizzaId = new Guid("faf6fe18-9035-4bcb-84ec-50502df3ea3e"),
                            Category = 5,
                            Description = "Mushrooms, Olives, Green Peppers, Onions, Mozzarella",
                            DougtType = "",
                            Name = "Nut-Free Pizza",
                            Price = 10.00m,
                            Toppings = "[]",
                            Vegan = false,
                            Vegetarian = false,
                            size = ""
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
